ICON_VARIANT_OUTLINED = "outlined"
ICON_VARIANT_ROUND = "round"
ICON_VARIANT_SHARP = "sharp"
ICON_VARIANT_SOLID = "solid"
ICON_VARIANT_TWOTONE = "twotone"

ICON_ORIGIN_HOST_MATERIAL = "material"
ICON_ORIGIN_HOST_ANTD = "ant-design"
ICON_ORIGIN_HOST_FONTAWESOME = "font-awesome"
ICON_ORIGIN_HOST_REFLECT = "icons.reflect-ui.com"
ICON_ORIGIN_HOST_RADIX = "icons.radix-ui.com"
ICON_ORIGIN_HOST_ICONSCOUT_UNICONS = "iconscout.com/unicons"
ICON_ORIGIN_HOST_GRIDA = "grida"

ICON_DEFAULT_SIZE = 24