ICON_VARIANT_OUTLINED = "outlined"
ICON_VARIANT_ROUND = "round"
ICON_VARIANT_SHARP = "sharp"
ICON_VARIANT_DEFAULT = "default"
ICON_VARIANT_TWOTONE = "twotone"

ICON_ORIGIN_HOST_MATERIAL = "material"
ICON_ORIGIN_HOST_ANTD = "and-design"
ICON_ORIGIN_HOST_REFLECT = "reflect"
ICON_ORIGIN_HOST_FONTAWESOME = "font-awesome"
ICON_ORIGIN_HOST_BRIDGED = "bridged"

ICON_DEFAULT_SIZE = 24